### ISSUE TITLE
[Suggestion]: Rename GraphQL Extension to .graphql from .gql

### ISSUE THREAD

**Issue by webberwang** [leebenson/reactql#103]
More of an enhancement than bug.

Reasons for change:
(1) .graphql is used internally at Facebook
https://github.com/facebook/graphql/issues/203

(2) Plugins by default use .graphql as syntax extension for highlight

**Comment by jonoirwinrsa** [comment]
Plus one for this. The Webstorm GraphQL plugin doesn't recognise the .gql extension - missed out on a week of auto-completed :)

**Comment by leebenson** [comment]
In 3.0.0 (released today), there's actually no `.gql` or `.graphql` by default at all. Instead, it's pure Typescript:

```ts
// Get local count state

// ----------------------------------------------------------------------------
// IMPORTS

/* NPM */

// GraphQL tag library, for creating GraphQL queries from plain
// template text
import gql from "graphql-tag";

// ----------------------------------------------------------------------------

// GraphQL query for retrieving the current count from local state
export default gql`
  {
    state @client {
      count
    }
  }
`;
```

If re-enabling `.gql` is important for local IDE linting, that's an easy addition to Webpack that I don't mind doing to the core kit. I'll close this for now but let me know if this is important to you.
