### ISSUE TITLE
Server sider rendering fails with mime type error running locally

### ISSUE THREAD

**Issue by reduxdj** [leebenson/reactql#104]
Is there a fix for this?

Refused to apply style from 'http://local.app.com:8081/assets/css/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to execute script from 'http://local.app.com:8081/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
32EwXtEWxDA?rel=0&origin=https://app.com&modestbranding=1:1 Error parsing header X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube: insecure reporting URL for secure page at character position 22. The default protections will be applied.
(index):1 Refused to execute script from 'http://app.com:8081/browser.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by reduxdj** [comment]
HI, this issue has been open for 2 months, can you provide any ideas why this error might come up.

**Comment by leebenson** [comment]
Sorry for the delay @reduxdj - the kit has undergone significant changes with 3.0.0, so this may or may not still be an issue.

Please clone the latest repo and see if it's still a problem. If so, feel free to re-open and I'll take a look.
