### ISSUE TITLE
Slow hot reload speeds compared to Create React App

### ISSUE THREAD

**Issue by webberwang** [leebenson/reactql#105]
Has anyone experienced this? My app isn’t that complicated, some SCSS and using Reactstrap.

A fresh install takes about 3s to compile, but after building the app, it’s taking up to 6-8s and becomes unbearable for development.

Everything else is amazing, just the slow compile time.

What factors affect compile time the most? Does loading several SCSS framework cost a lot of resources? 

I went back to a CRA project and was shocked at how fast it was. It must be something to do with SSR.

**Comment by leebenson** [comment]
If you're pulling in a few different SASS frameworks, then yeah, things generally can be quite slow.

Bumping to Webpack 4 should ultimately speed things up, and there's probably some better caching we can be doing in the meantime. I'll take a look at this eventually. In the meantime, if anyone has any faster tweaks, feel free to submit a PR.

**Comment by webberwang** [comment]
Thanks, does development render the server side components? Could there be some optimization done there if we only render the client side for production?

**Comment by leebenson** [comment]
In the new 3.0.0 kit, yes, full SSR occurs during dev too. With Styled Components (something else the new kit includes), hot reloading is generally super fast - a second or less.

Try it out and see what you think.
