### ISSUE TITLE
Connect to mongodb while starting server

### ISSUE THREAD

**Issue by Kamill90** [leebenson/reactql#107]
Hi. It is not an issue. I just wonder where should I write connection function to MongoDB so that app would connect to a database while starting the server. The most convenient place seems to be kit/entry/server.js but I would like to know your opinion. 
Example with snippet would be great.

**Comment by leebenson** [comment]
In the new 3.0.0 kit, see [src/runner/app.ts](https://github.com/leebenson/reactql/blob/master/src/runner/app.ts) for how the app is currently wired together. You can create attach a MongoDB server to that, and then set-up middleware to feed through the connection to route handlers.

I don't have any snippets off hand, but StackOverflow could probably help. If you're looking for commercial support, give me a shout.
