### ISSUE TITLE
Any plans to implement ApollographQL 2.x and Apollo Boost?

### ISSUE THREAD

**Issue by imsarvesh** [leebenson/reactql#114]
Any plans to implement ApollographQL 2.x and Apollo Boost?

**Comment by Sybio** [comment]
<Query> component would be so great !

**Comment by leebenson** [comment]
Yep, done in 3.0.0 👍 

Clone the latest repo and you'll find `<Query>`, `<Mutation>` and a bunch of other goodies.

I didn't add Apollo Boost, instead preferring to add each config explicitly for better control.

**Comment by Sybio** [comment]
Awesome work ! 🥇 

Can we consider the repository maintained (or still deprecated) ?

Also did you planned to tag the last commit ?

**Comment by leebenson** [comment]
@Sybio - yep, you can now consider the project maintained. I'm using this actively in production, so it'll generally maintain parity with what I'm working on locally.

There's no longer a CLI, so the `reactql` NPM module is now deprecated.

**Comment by leebenson** [comment]
@Sybio - See also https://github.com/leebenson/reactql/issues/10#issuecomment-410223367 for a rundown of the changes.

**Comment by Sybio** [comment]
Very clear ! Thanks.

**Comment by imsarvesh** [comment]
Awesome.. Thanks
