### ISSUE TITLE
On refresh the contents of the page all get larger

### ISSUE THREAD

**Issue by ryanelkholy** [leebenson/reactql#115]
I have played around with ReactQL a bit and made a sample page. I noticed that at random times id I refresh the page the contents of the page all get larger. Almost as if the browser has been zoomed in, but it has not. And when this occurs, I can re-run the project and it is still larger. Even if I use a new browser. It eventually goes back to normal randomly as well. Any idea what I may have done or if this is a known issue?

**Comment by leebenson** [comment]
This shouldn't happen anymore, with the new 3.0.0 release. There's full server-side rendering even in development, so all styles will be loaded first, avoiding the flash of unstyled content.

**Comment by ryanelkholy** [comment]
I am on version 4.10.0 and it is still happening. I noticed that randomly
when loading the page that the entire web app appears zoomed in. I checked
all the web browser settings and it remains at 100% and is not zoomed. When
the page loads normally I can get it to happen simply by refreshing the
page. I did some tinkering around and realized that when this did randomly
happen I could just play around with the following line of code in my css:

html {

    font-size: 62.5%;

}

All I have to do is change the percentage to any number and rebuild, then
change it back to 62.5% and rebuild and it would go back to normal. Until,
that is, I refreshed the page. At which point it would appear zoomed again.

Do you have any idea how to solve this issue so that the appearance and
size of things in my web app remains consistent?

**Comment by leebenson** [comment]
Ignore the version numbers. `4.1` refers to the old React CLI, which is no longer valid.

Follow the instructions [here](https://github.com/leebenson/reactql#quick-start) to grab the new kit and spawn a server

**Comment by ryanelkholy** [comment]
What is the best way to just update my current project?

**Comment by leebenson** [comment]
You can't directly upgrade, I'm afraid. This is a totally different code base. It's a starter kit and isn't intended to be upgraded.

**Comment by ryanelkholy** [comment]
Understood. Thanks!
