### ISSUE TITLE
Check .js imports

### ISSUE THREAD

**Issue by leebenson** [leebenson/reactql#119]
The current config _should_ support plain `.js` imports, but this hasn't been thoroughly tested. Check that it works with the current TS config by creating a sample component in the kit.

**Comment by bmschwartz** [comment]
Rewrote count.tsx as `.js` component and both the mutation and query work fine. I can post the code if you like.

**Comment by leebenson** [comment]
Thanks, but no need. As long as `.js` importing works, this issue is solved.
