### ISSUE TITLE
import third party package has error: window is not defined

### ISSUE THREAD

**Issue by ryanyu104** [leebenson/reactql#120]
when I import plugin in my project
code: import ReactMic from "react-mic"
report error: window is not defined.

I know it is the server environment, but how can I solve this error?  THX

**Comment by klarstrup** [comment]
The problem is in the `react-mic` codebase: https://github.com/hackingbeauty/react-mic/blob/3edd1e9a651a0afdd35aaed23e33449fec6eb0b1/src/libs/AudioContext.js#L1

Here there is unguarded access to the window global at the top level. You'll need to submit a PR to react-mic to fix this.

**Comment by ryanyu104** [comment]
@klarstrup  THX, I get it. I will close this issue.
