### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jimmyjamieson** [leebenson/reactql#122]
I'm giving this a try on ubuntu and windows 10 pro, and it won't compile.

```
webpack: Encountered errors while compiling. Reload prevented.
_ @ log.js:59
errors @ client:60
(anonymous) @ socket.js:49
log.js:59 ｢hot｣ (client) ./node_modules/graphql/index.mjs 64:0-70:117Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)    at HarmonyExportImportedSpecifierDependency._getErrors 
```

There's a heap of these errors from different scripts, and I'm running the latest node LTS.

**Comment by leebenson** [comment]
Are you using plain `.js` imports in your project? 

On first glance, [this](https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574) seems like it might be the fix.

Per https://github.com/leebenson/reactql/issues/119, I need to check for support for plain `.js`. I'm personally using `.ts|tsx` throughout projects, so this needs properly testing.

**Comment by jimmyjamieson** [comment]
This is just running the example. I've not added anything :)

**Comment by leebenson** [comment]
Found the fix.

`.mjs` was missing from the Webpack `resolve.extensions` option, which meant that ES6 module support was being deferred to Node.

Since you're using the LTS branch (v8.x), there _is_ no ES6 support, hence the build error. Anyone using v10.11+ wouldn't have seen it.

Will patch and push the latest version now.

**Comment by leebenson** [comment]
Fixed in [3.3.0](https://github.com/leebenson/reactql/releases/tag/3.3.0)

Try this (in Ubuntu - for Windows, download/unpack the tar manually):

```
wget -qO- https://github.com/leebenson/reactql/archive/3.3.0.tar.gz | tar xvz
cd reactql-3.3.0
npm i
npm start
```

**Comment by jimmyjamieson** [comment]
Awesome, I'll give it another spin after work and check.

Also, i'll maybe mention as well, it might be worth updating to styled-components 4.0

**Comment by leebenson** [comment]
I'm certainly planning on bumping to Styled Components v4. It's still in beta and would require some code changes, so it's something I'll look at in the coming weeks.
