### ISSUE TITLE
Typescript? Seriously? Over Flow or ReasonML?

### ISSUE THREAD

**Issue by quadsurf** [leebenson/reactql#125]
I love what you've done, but will hold off until you replace Typescript with ReasonML. Is ReasonML even roadmapped for ReactQL?

**Comment by bmschwartz** [comment]
Come on, this is a free product. Stop whining and making demands for something you are not paying a dime for. Make a fork and rewrite it in ReasonML yourself.

**Comment by leebenson** [comment]
> Typescript? Seriously?

Yes. Seriously.

> Is ReasonML even roadmapped for ReactQL?

Nope.

**Comment by quadsurf** [comment]
Ya that definitely came off wrong, my apologies.

**Comment by leebenson** [comment]
I'm a fan of ReasonML, but for this project, I wanted a Javascript starter kit that could directly interop with specific stack choices - Styled Components, etc, and be an easy insert for existing JS projects without a ton of bindings/abstractions.

IMO, Typescript offers a good balance of type safety for building out the kit (i.e. my job) with decent _optional_ type safety for the developer (i.e. don't like TS? just import a plain `.js` script). But it's still just a superset of regular JS, so teams with a large JS investment don't need to start from scratch.

ReasonML, OTOH, would offer _awesome_ type safety, at the cost of an obtuse syntax. If type safety were my only goal (or even top 3), I'd probably opt for it from the outset. But a more important factor of this project is this being readable and usable by the JS community at large.

Maybe one day I'll spin-off something similar with ReasonML front and center, but it's not currently on my radar.
