### ISSUE TITLE
issue with accessing window.localStorage in development mode

### ISSUE THREAD

**Issue by arif-hanif** [leebenson/reactql#126]
I am trying to use the apollo cache persist package in development but getting a window is not defined for localstorage access on web.

```
persistCache({
  cache,
  storage: window.localStorage,
});
```

ℹ ｢hot｣: WebSocket Client Connected
ℹ ｢hot｣: webpack: Bundle Invalidated
ℹ ｢wdm｣: Compiling...
ℹ ｢hot｣: webpack: Bundle Invalidated
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: webpack: Compiling Done
✔ Running on http://localhost:3000
ℹ ｢wdm｣: Compiled successfully.
Error: window is not defined

**Comment by leebenson** [comment]
ReactQL runs on both the server and in the browser. Since `window` means nothing to the server, guard against it running outside of the browser like so:

```js
if (!SERVER) {
  persistCache({
    cache,
    storage: window.localStorage,
  });
}
```
