### ISSUE TITLE
Static and production deploy

### ISSUE THREAD

**Issue by elie222** [leebenson/reactql#137]
I see there's a way to do a static deploy to Netlify, and there's also SSR with something like a Docker deploy. Can the two be combined? Or is it one or the other?

I like the Netlify deploys, easy and takes all load off my servers for serving static content. If I'm mostly interested in the static frontend deployed on Netlify and don't care too much for the SSR features, is this boilerplate still useful?

**Comment by leebenson** [comment]
Netlify is a static host. The only option you have with them is to serve pre-existing files - i.e. the `index.html` that 'static' mode creates, along with the pre-compiled JS bundle.

If you want to actually run a Node.js Koa web server (which is what's used for server-side rendering), then you would need a runtime to parse that. Docker is the easiest way to get that spinning (and there's a `Dockerfile` for doing just that), or you could simply copy over the source files, run `npm i` on your hosted machine, and put `npm run production` in an init.d script to boot on start-up.

As for whether or not the boilerplate is useful - regardless of whether you opt for static compilation or SSR, the flow that Webpack takes to crunch through the source files and spit out the `.js`, image and CSS assets at the end of it, is almost entirely the same. The only difference with SSR mode is that you also get a `server.js` generated too, which acts as Koa middleware for parsing HTTP requests and rendering React on the server.

So you're still getting the full benefit of all the tooling that ReactQL provides - the Webpack set-up, React mounting/rendering, CSS/SASS/LESS/Emotion tooling, Typescript source code, hot-code reloading in development, the ability to import non-JS files like images into your source and use them natively, dynamic `import()`s for code splitting, and everything else listed on the readme.

Those benefits still support your development experience, and the ultimate layout of your resulting code, whether or not you opt to enable SSR.
