### ISSUE TITLE
React Hooks in Function Component Not Working

### ISSUE THREAD

**Issue by chrischen** [leebenson/reactql#148]
I'm trying to use a functional component in the React.PureComponent render method, and if the functional component uses a hook such as useState, it gives this error:

`Invariant Violation: Hooks can only be called inside the body of a function component. `

I've ruled out the following issues:
1) Old version of react-dom or react (16.8.2 is being used)
2) Duplicate instances of React.

```
import * as React from "react";
import { useState } from "react";

const Query: React.SFC = ({ query, children }: { query: string, children: any }) => {
  const [inputValue, setInputValue] = useState("default text");

  return <>
  </>;
}
export default Query;
```

I'm testing it inside the example/index.tsx file:

```
// Say hello from GraphQL, along with a HackerNews feed fetched by GraphQL
class Index extends React.PureComponent<{}, IIndexState> {
  public render() {
    return (
      <>
        {/* Note: The <h1> style will have a yellow background due to @/global/styles.ts! */}
        <h1>Hi from ReactQL</h1>
        <Query>
        </Query>
      </>
    );
  }
}

export default Index;
```

**Comment by klarstrup** [comment]
Update react hot loader

**Comment by chrischen** [comment]
I found out the issue (I had already update react-hot-loader). It turns out it was because I was using loadable-components for SSR and I was injecting the js script files two times (one from the default as per your boilerplate, and again from the loadable-components collected chunks).
