### ISSUE TITLE
Move to @babel/preset-typescript

### ISSUE THREAD

**Issue by chrischen** [leebenson/reactql#152]
I'm not sure what's everyone's opinions on moving to preset-typescript, but I had encountered some hard to debug issues with using babel-plugin-macros with js-lingui library that was caused by ts-loader. Barring other reasons, I think simply reducing the number of moving  parts is a good "pro" of getting rid of ts-loader.

I managed to fix it by moving off of ts-loader and to use preset-typescript.
This is what I had to add on the babel side to make the boilerplate work without ts-loader and just with babel.
```
"presets": [
                  ["@babel/preset-env", { useBuiltIns: "usage" }], // Can also use useBuiltIns: "entry" but then you'd have to import "@babel/polyfill" one time somewhere in the app.
                    "@babel/preset-typescript",
                    "@babel/preset-react"
                ],
                plugins: [
                  ["@babel/plugin-proposal-decorators", { legacy: true}],
                  ["@babel/proposal-class-properties", { loose: true }],
                  "@babel/proposal-object-rest-spread",
                  "@babel/plugin-syntax-dynamic-import",
                  "react-hot-loader/babel",
                  "emotion"
                ]
```

**Comment by chrischen** [comment]
Seems like this move would break the namespaces support.

**Comment by leebenson** [comment]
Thanks @chrischen. Added in [v4.5](https://github.com/leebenson/reactql/releases/tag/4.5.0) just now.
