### ISSUE TITLE
3.5 - Questions on Apollo queries not resolving

### ISSUE THREAD

**Issue by reduxdj** [leebenson/reactql#158]
Hi there,

We're still using the branch of 3.5 in a big project, (pardon us, it's a big project and we haven't had the resources to upgrade, also the version 4 is drastically different, and we'd have to rewrite our server, that's a topic for another thread). 
Currently, I'm fighting with some common problems in metadata and react-helmet, and refactoring the app to use react-helmet-async. In our testing, we noticed that while while we updated our code to support streaming, it seems that our queries don't populate before our components render, which means our metadata which gets written to the head, incorrectly  at first write. 

My question is, isn't this the purpose of graphql decorators to populate the data  with the result before the page renders? In all our testing every query seems to be empty, at least once, before the respective component renders.

For example:

```
@connect(
  (state) => ({user: userSelector(state),
    token: userTokenSelector(state),
    userExists: userExistsSelector(state)}),
  (dispatch) => ({
    actions: bindActionCreators(UserActionCreators, dispatch),
  })
)
@compose(
  withRouter,
  graphql(BlogBySlug, {
    name: 'blogBySlug',
    options: ({
      match: {
        params: {slug},
      },
    }) => ({
      skip: !slug,
      variables: {slug},
    }),
  }),
  graphql(BlogPreview, {
    name: 'blogPreview',
    options: ({
      location: {search},
      match: {
        params: {slug},
      },
    }) => ({
      skip: !search.includes('id') && !slug,
      variables: {id: _.get(parseSearchQuery(search), 'id')},
    }),
  })
)
```

----

```
render() {
    const {
      data: {loading, error},
    } = this.props

    console.log(this.props.data)
    const blog =
      _.get(this.props, 'blogBySlug.blogBySlug.blog') || _.get(this.props, 'blogPreview.blogPreview.blog')
```

This is empty which is confusing.

Is this proper?

Also in my server code, i notice that the apollo data is never populated, in the ctx store, while the redux data is?

Thanks for any help. (throwing out all assumptions on how me thinks apollo works.

**Comment by reduxdj** [comment]
I found the issue, it was the react error boundary, it was stopping our queries from working..

**Comment by leebenson** [comment]
Glad you found the issue!
