### ISSUE TITLE
4.3.1.tar.gz not working

### ISSUE THREAD

**Issue by temp3l** [leebenson/reactql#163]
hi,

I just downloaded https://github.com/leebenson/reactql/archive/4.3.1.tar.gz

and ran: npm install && npm start

with: 
node/11.0.0 & node/12.2.0
npm -v 6.9.0

I'm getting this error: (disabling sourceMaps did not help)
```
reactql-4.3.1/node_modules/ts-node/src/index.ts:240
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/hotServerMiddleware.ts:88:20 - error TS2532: Object is possibly 'undefined'.

88   const filename = assetsByChunkName.main || "";
                      ~~~~~~~~~~~~~~~~~

```

* Also cloned current master -> live-reload is not working (have to refresh browser manually)
* browser gets notified about code-change in a split second, but won't reload...
* browser shows warnings

log.js:59 ｢hot｣ Warnings while compiling.
_ @ log.js:59
warnings @ client:87
(anonymous) @ socket.js:49
log.js:59 ｢hot｣ (server) ./node_modules/encoding/lib/iconv-loader.js 9:12-34Critical dependency: the request of a dependency is an expression

anyway, awesome project !!  ;) good luck

**Comment by leebenson** [comment]
Sorry about that! This was fixed in 4.4.0 this morning. I've updated the readme to reflect. Feel free to re-open if you run into further issues.

**Comment by temp3l** [comment]
reactql-4.4.2: yarn dev

still no reload, but warning disappeared
create-react app and other are working correctly

**Comment by leebenson** [comment]
@temp3l if you're having other, non-related issues, please open separate issues with the necessary detail to diagnose, so we can focus on each individually.
