### ISSUE TITLE
Can't run project - quick start

### ISSUE THREAD

**Issue by sky790312** [leebenson/reactql#165]
I follow the quick start. But I can't open the project. I face the following message:

```
warning: couldn't find native brotli support in zlib library. trying to fall back to iltorb.
```

And I open the localhost:3000,  it just say: There was an error. Please try again later.

I believe the server has something wrong. Is there anything I missing?

(I'm using node v10.15.3 mac OSX)

**Comment by leebenson** [comment]
Bump to Node 11. It's most likely not the warning that's causing the issue, but the use of `.flat()` per #144. Try that and feel free to re-open if you're still having issues.
