### ISSUE TITLE
[v3.2.0] How to disable SSR?

### ISSUE THREAD

**Issue by dickyindra** [leebenson/reactql#168]
I have a project build with ReactQL v3.2.0, i got problem production mode in sometime shows error "Maximum call stack size exceeded" with kill my running project.

I will disable ssr to be easily tracked error.

**Comment by leebenson** [comment]
I’d recommend using the 4.x branch of ReactQL since the tooling is up to date. The stack in v3 is now quite old and unsupported.

In v4, you can disable SSR by running `npm run dev:static`

**Comment by dickyindra** [comment]
I want migration my project to ReactQL v4, but i don't know step to migrate ReactQL from v3 to v4.

Do you make documentation for migrating ReactQL v3 to v4?

**Comment by leebenson** [comment]
The easiest thing to do is start a new project with the new kit, then copy over your own `src` components into the new project.

There’s no direct upgrade path since ReactQL is intended to be a starter kit and not an upgradable framework.
