### ISSUE TITLE
Adding Material UI Button cause emty page

### ISSUE THREAD

**Issue by Fivedark** [leebenson/reactql#171]
The Material UI Button or List crashes ReactQL. Other Material UI components like Card and Chip working fine.

**Steps to reproduce:**
1. checkout current version 4.5.1
2. run `yarn add @material-ui/core`
3. add following lines to Example component
   at line 17: ` import {Button} from "@material-ui/core";`
   at line 48: `<Button>Test</Button>`
4. run `yarn start`
5. start your browser (newest Firefox or Chrome) and call `localhost:3000`

**Expected result:**
To see a button under the headline.

**Actual result:**
Empty page with a lot of warnings and errors in browser console. Last error is:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

Check the render method of 'TransitionGroup'.
```

**Comment by leebenson** [comment]
According to https://material-ui.com/getting-started/usage/, the correct import is:

```ts
import Button from '@material-ui/core/Button';
```

Try that.

**Comment by iweurman** [comment]
Also have this issue for both import styles:
import Button from '@material-ui/core/Button';
import { Button } from '@material-ui/core';
