### ISSUE TITLE
import X from  "y"

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [leebenson/reactql#174]
VsCode all **import X from  "y"** print error.
![image](https://user-images.githubusercontent.com/696713/62956409-9245ce00-bdfb-11e9-8860-492189158e0d.png)

Need " -> '

![image](https://user-images.githubusercontent.com/696713/62956441-9f62bd00-bdfb-11e9-8f64-9e3bcddb33dc.png)

**Comment by leebenson** [comment]
I'm not able to reproduce this locally. Seems very odd that switching from double quotes to single quotes would make any material difference - both are valid JS/TS representations of strings.

Usually this kinda thing indicates either:

a) VSCode hasn't caught up. Try restarting your editor.

b) There's some linting plugin that dislikes one string style vs. another. I use Prettier and double-quote strings. The fact that `"path"` isn't yielding any errors in your screenshots, probably means this is not a linting issue.

I've guess (a) above.

**Comment by Pomazan-Bogdan** [comment]
Prettier
