### ISSUE TITLE
Example for a MongoDB based server

### ISSUE THREAD

**Issue by the-petrolhead** [leebenson/reactql#180]
Hi,

I'm fairly new to JS/TS client-server development. Pardon my choice of words.

@leebenson 
ReactQL seems to be a great starter for client. Thanks for your efforts.
I already started exploring it and wondering if there is an example of hooking up a MongoDB-GraphQL server?

I'm asking this since ReactQL as frontend starter has made some great choices in terms of developer productivity. I would want to ease the server development as well.

Any recommended starter projects exist for Mongo-GraphQL? I was able o find following but not sure how could I hook them in the ReactQL project.
https://github.com/the-road-to-graphql/fullstack-apollo-react-boilerplate
https://github.com/arackaf/mongo-graphql-starter

**Comment by leebenson** [comment]
There's no example of bolting on a GraphQL server in the kit, but you can bolt one on to the `router` at https://github.com/leebenson/reactql/blob/master/src/runner/app.ts

You'd basically create a `/graphql` endpoint (or whatever you want to call it), and add in either the [GraphQL reference implementation](https://github.com/graphql/graphql-js), or a more complete framework like [Apollo Server](https://www.apollographql.com/docs/apollo-server/) to handle your queries.

Adding MongoDB would be a case of applying that logic inside the GraphQL resolver, based on whatever business rules make sense. You could use an ORM or the standard MongoDB lib for this.
