### ISSUE TITLE
How to pass environmental variables to the application's client bundle?

### ISSUE THREAD

**Issue by birdiesanders** [leebenson/reactql#91]
I'm unsure of how I can get the client bundle to connect back to the host it was served from, I have a working implementation where I set the variable in the package.json run build script, but this is rather inelegant, and I would like to simply have it use the hostname it was served from. How can I get this working with the webpack config in reactql?

**Comment by leebenson** [comment]
There's a ton of changes introduced in 3.0.0, one of them is the reliance on environment variables to set up hosting. The ethos of the kit now is simply to go in and make whatever changes you want, direct to the code. If env vars make sense to your set-up, then you can add them as needed.
