### ISSUE TITLE
Suggestion: Testing guidance

### ISSUE THREAD

**Issue by dougajmcdonald** [leebenson/reactql#94]
I see there is a config for jest an some mention of coverage, but I don't see anything on testing in the docs.

I think it'd be nice to see any of the following:

- A testing section in the docs
- An example test, so `npm test` does something
- Coverage turned on by default
- Maybe some more complex test examples which touch on graphql component testing etc

**Comment by istinspring** [comment]
i can't make tests work, it unable to import "scss" files.

 ```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import "src/styles/base.scss";
                                                                                             ^
    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/components/sections/header.jsx:7:15)
      at Object.<anonymous> (src/__tests__/header.test.jsx:3:15)
```

**Comment by jonoirwinrsa** [comment]
@istinspring You can get around that issue with this package: https://www.npmjs.com/package/jest-css-modules

The github page suggests that you might not need it however I wasn't able to get their alternative method to work.

**Comment by istinspring** [comment]
@jonoirwinrsa i resolved it via proxy object.

```javascript
{
  moduleNameMapper: {'^.+\\.(css|less|scss)$': 'identity-obj-proxy',
  }
}
```

in `jest.config.js`

**Comment by jonoirwinrsa** [comment]
😮 thanks - that works better.. Keeps the classnames in-tact

**Comment by leebenson** [comment]
There's currently no test runner in the new 3.0.0 kit, but adding one will be fairly trivial when I've settled on an option. There's a lot of changes since the last ReactQL version, so I ripped it out for speed. Feel free to add whichever you like best.
