### ISSUE TITLE
Suggestion: CI guidance

### ISSUE THREAD

**Issue by dougajmcdonald** [leebenson/reactql#95]
It'd be nice if there was some documentation covering common setups for CI etc. 

For example you have a travis.yml in the project which builds the image but it doesn't run the tests.

I think ideally I'd want the travis.yml on PR's to run the tests and then on merges into master to build the image. In fact I'd go as far to say this should perhaps be the default? Thoughts?

**Comment by leebenson** [comment]
That's a good idea. All the current ReactQL documentation is out of date anyway, with the release of the 3.0.0 kit today. So I'll probably need to bin it all and start again, and that would be a good place to put deployment help.

FWIW, I removed travis.yml from the current kit to avoid it being too opinionated.
